### ISSUE TITLE
API Framework

### ISSUE THREAD

**Issue by asclines** [TTUSDC/CPCEEDWebAppBackend#1]
We need to decide on a framework for making a RESTful API.  
Three options I have found are:
- [restify](http://restify.com/)
- [express](http://expressjs.com/)
- [loopback](https://loopback.io/)

Thoughts on these frameworks or another option?

**Comment by ryanfaulkenberry100** [comment]
"In short, I wrote restify as I needed a framework that gave me absolute control over interactions with HTTP and full observability into the latency and characteristics of my applications. If you don't need that, or don't care about those aspect(s), then it's probably not for you." -Restify Guy
Is this functionality necessary? If not we can drop restify and narrow the discussion down, or vice-versa.

**Comment by asclines** [comment]
@ryanfaulkenberry100 Thats an excellent point.  With our app, it is safe to assume we wont ever have a truly high volume amount of traffic that would require that kind of micromanagement.

**Comment by asclines** [comment]
One thing I want to point out is we may have to consider the possibility that the server will also host the app if we cant continue to use Firebase for that. In which case, Express might be the better option.

**Comment by zachlefevre** [comment]
I'm just reading through forums like these: http://stackoverflow.com/questions/17589178/why-should-i-use-restify
They say express is faster, but restify is easier to diagnose, monitor and is less likely to drop requests.
I doubt any of our API requests will be heavy enough to justify the need for an all out express server, and I think the extensive restify monitoring packages will be more valuable to us than speed.

**Comment by asclines** [comment]
Closing as in meeting today, we determined Express best fit our needs.
