### ISSUE TITLE
Create Report manager 

### ISSUE THREAD

**Issue by asclines** [TTUSDC/CPCEEDWebAppBackend#14]
Now that in #10 the model and schema for Reports is done, the logic between the database and router needs to be developed.

Filename: `report-manager.js` (WIP, if someone has a better naming scheme for this part of the stack please share)

Purpose: All the logic between database and router should be done here.
This will include things such as check role-based security, any data cleaning, making the database calls, etc..

The methods here should line up with the methods declared [here](https://github.com/TTUSDC/CPCEEDWebAppBackend/wiki/Report-Endpoint-API-Reference).

**Comment by jmtaber129** [comment]
Since we have ```report-models.js``` and now ```report-manager.js```, should ```router.js``` also be changed to ```report-router.js```?

**Comment by asclines** [comment]
@jmtaber129 that is one way to look at it. This file name could also be `manager.js` instead if you prefer.

**Comment by jmtaber129** [comment]
I think I like having all the report files prefixed with ```report-```.
