### ISSUE TITLE
Research User Authentication 

### ISSUE THREAD

**Issue by asclines** [TTUSDC/CPCEEDWebAppBackend#15]
We have no idea how we are handling user & session authentication. Handle this.

Checkout [here](https://github.com/TTUSDC/CPCEEDWebApp/issues/20) for the front end discussion on this.

Requirements:
- Works with Node.JS and MongoDB
- Has a generic username, email login so the login system can be subbed in with TTU's in the future if needed.

**Comment by the-pat** [comment]
Here are a handful of auth frameworks that work with NodeJS and MongoDB:

- [LockIt](https://github.com/zemirco/lockit)
- [Passport](http://passportjs.org/)
- [CloudRail](https://cloudrail.com/)
- [MongoDB](https://mongodb.github.io/node-mongodb-native/2.0/reference/connecting/authenticating/)

Thoughts are appreciated.

**Comment by the-pat** [comment]
After a brief glance, I am against using MongoDB's built in auth. The default mechanism is [SCRAM-SHA-1](https://en.wikipedia.org/wiki/Salted_Challenge_Response_Authentication_Mechanism) which seems a little lacking. The other mechanisms might be useful, but I will continue looking at the other frameworks.

**Comment by asclines** [comment]
@the-pat Good point about the built in auth. At the end of the day, since you are the one who will be implementing this, as long as it meets the above requirements, all will be good. 
'
That being said, LockIt looks good

**Comment by asclines** [comment]
@the-pat any updates on this?

**Comment by the-pat** [comment]
Sorry for the hiatus.

I have updated the wiki to reflect the auth endpoints and am moving forward with `lockit`.

**Comment by the-pat** [comment]
After our whiteboard talk:

# Methods
## login(email, password)

1. Look up user in DB.
2. Check `if hash(password) == DB.password_hash`.
3. If true, generate, save, and return session token. Otherwise, return error message.

## logout(token)

1. Look up token in DB
2. Delete entry

## create(email, password, role)

1. Look up email in DB
2. If entry exists, return error message (duplicate). Otherwise, create a new `auth_user` entry with `{ email, hash(password), role }`

# Schema
We also need two database tables to manage session authentication.

## `auth_user`
```javascript
{
  email: String,
  password_hash: String,
  role: Enum,
}
```

## `session_tokens`
```javascript
{
  token: String,
  role: Enum,
}
```
---
If nothing needs to change, we are ready to move forward with user auth.

**Comment by asclines** [comment]
@the-pat how much of that needs to be rolled out for this project vs. comes in a library?

**Comment by the-pat** [comment]
I don't think we need to do much, but I'm not 100% sure.

**Comment by the-pat** [comment]
@asclines, Lee showed me [this](https://github.com/sahat/hackathon-starter) repo.

It has a really good example for auth using `passport`.

**Comment by the-pat** [comment]
Update on auth.

# Endpoints

## Create

Given an email, password, and role create an [`AuthUser`](#authuser). Does not log the user into the system.

## Login

Given a valid user email address and password, create a [`Session`](#session) and return a token.

## Logout

Given a valid user token, end the user session. Logs the user out of all logged in sessions.

# Middleware

## Verify

Given a user token, ensure that the token has a valid signature and is still an active session. Add the `decoded` object to the `req` object. The `decoded` object has the following structure:
```javascript
decoded = { email, role };
```

# Models

## AuthUser
```JSON
{
  "email" : STRING,
  "password" : STRING,
  "role" : ENUM/STRING
}
```

## Session
```JSON
{
  "email" : STRING,
  "token" : STRING
}
```
