### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by the-pat** [TTUSDC/CPCEEDWebAppBackend#8]
After putting more thought/research (aka reading stackoverflow), I think we need to talk more about our endpoints.

My thoughts in brief:

- Endpoints should be made up of nouns; the HTTP verb determines what to do (get, create, etc.)
- Required parameters should be a part of the endpoint; optional parameters should be a part of the query string (i.e. `/event/1234?sortby=date`)
- Parameters in the endpoints give us primitive data types (int, string, bool, etc); the request body passes objects

Thoughts?

**Comment by asclines** [comment]
I do agree with that.  Pretty sure the endpoints with the nouns were already being set like that but the required parameters point.  I really like that point.  Definitely should do that

**Comment by asclines** [comment]
Has this been settled?

**Comment by the-pat** [comment]
Yes?

**Comment by asclines** [comment]
Then this issue is resolved.
